### ISSUE TITLE
Search function walk.all and delete not empty folders

### ISSUE THREAD

**Issue by tarkett2018** [az0/cleanerml#140]
I want to configure the constellation to delete all directories (with included files) with ending strings like (1), (2), (3), ...

My actual configuration is
    `<action command="delete" search="walk.all" path="C:\Tools\cloud_open\apps\" regex=" \(\d\)" />`

The file structure is
C:\Tools\cloud_open\apps\FirefoxPortable\...
|-------------------------\BleachBit-Portable\...
|-------------------------\LibreOfficePortable\...

Example directories which should be deleted:
- C:\Tools\cloud_open\apps\FirefoxPortable\Data\Firefox\safebrowsing (1)\
- C:\Tools\cloud_open\apps\FirefoxPortable\Data\Firefox\safebrowsing (3)\
- C:\Tools\cloud_open\apps\LibreOfficePortable\Data\LibreOffice\user\extensions\tmp (1)\

So I want to clean the complete structure C:\Tools\cloud_open\apps and it must be walk through all directories. The files inside the directories should also be deleted, independent from the defined regex.

My problem was, that it works only, if the directories are empty. How can I change the configuration that it deletes also the included files?

**Comment by az0** [comment]
At a glance, my first advice is to try `wholeregex` instead of `regex`, so the action matches all the files.  The [BleachBit 1.12 release notes](https://www.bleachbit.org/news/bleachbit-112) have a bit more information. Please try it with a preview first, of course. :)

**Comment by tarkett2018** [comment]
Many thanks. In my first tests it works fine.

**Comment by az0** [comment]
Thx for the reply. I will close this ticket
