### ISSUE TITLE
[linux] Clean trashes for non-home partitions

### ISSUE THREAD

**Issue by nodiscc** [az0/cleanerml#25]
From http://standards.freedesktop.org/trash-spec/trashspec-0.8.html:

> (2) If an $topdir/.Trash directory is absent, an $topdir/.Trash-$uid directory is to be used as the user's trash directory for this device/partition. $uid is the user's numeric identifier.

Search the filesystem for directories that match `\.Trash.*` and delete their contents.

**Comment by Tobias-B-Besemer** [comment]
@nodiscc, why you gave up ??? I guess it should be now possible with walk.all and wildcards... E.g.:

`<action command="delete" search="walk.all" path="/media/*/.Trash*"/>`

If you will work again on it, and I can help you, let me know!

**Comment by nodiscc** [comment]
Sorry, this issue was old/low-priority for me and I had given up on it a while ago; was just cleaning my todo list.
Your solution works perfectly so far, thank you.
I have sent a pull request https://github.com/az0/cleanerml/pull/252

**Comment by Tobias-B-Besemer** [comment]
No prob! You're welcome! :-)
