### ISSUE TITLE
Please create a release

### ISSUE THREAD

**Issue by francoism90** [az0/cleanerml#250]
Could you please create a release or tag? :)
I would like to provide a stable package in AUR (Arch Linux).

**Comment by az0** [comment]
How about the [v2.2 tag](https://github.com/bleachbit/bleachbit/releases/tag/v2.2)?

**Comment by francoism90** [comment]
@az0 I assume it's OK to distribute this over AUR? :)
Any license or any thing I should be aware of?

Thanks for creating the tag.

**Comment by az0** [comment]
V2 2 is a final release. It's the usual GPL v3 license. It's good to release

**Comment by Tobias-B-Besemer** [comment]
@francoism90, I think @az0 mean, you can pack the folder https://github.com/az0/cleanerml/tree/master/release and release it as v2.2 beside BleachBit v2.2.

**Comment by Tobias-B-Besemer** [comment]
@francoism90, have you already created your package?
If you wait some days more, we maybe get BiglyBT, SMPlayer & Tor stable and you can include it already... ;-)
