### ISSUE TITLE
search=path is not supported by bleachbit

### ISSUE THREAD

**Issue by jose1711** [az0/cleanerml#262]
https://github.com/az0/cleanerml/blob/8d9976419844e0e5eb832b2d4859e82997dead02/release/less.xml#L34

and not described in documentation either: https://docs.bleachbit.org/cml/cleanerml.html. the same issue is with gmrun cleaner.

**Comment by Tobias-B-Besemer** [comment]
Here is a new, bigger & better doc to CleanerML I'm working on:
https://github.com/LV-Crew/bleachbit-docus/blob/CleanerML-v2.0-Docu/_posts/cleanerml_v2.0.md

DK how get cleaner get it into "release" - think @az0 should move it to "pending".

**Comment by az0** [comment]
@jose1711 Thanks for pointing this out. I fixed this plus many similar errors.

`search="path"` is not documented because it's invalid

**Comment by Tobias-B-Besemer** [comment]
@az0, can you document "make tests"?

**Comment by az0** [comment]
@Tobias-B-Besemer 

Document what it does, how to do it, or something else?

**Comment by Tobias-B-Besemer** [comment]
What it does, how to do it and that it is recommended after writing a cleaner.
Can you make a small PR with some lines and push it here: https://github.com/LV-Crew/bleachbit-docus/blob/CleanerML-v2.0-Docu/_posts/cleanerml_v2.0.md ???

**Comment by az0** [comment]
@Tobias-B-Besemer  How about this https://github.com/az0/cleanerml/commit/fb6a98bc6aa24e3f4fb6dfabc424b98a794e1374 ?

**Comment by Tobias-B-Besemer** [comment]
However you like!

But think we should get it into the other doc at any point too, finish the doc and push it to your repo...
