### ISSUE TITLE
New bleachbit release including cleaners?

### ISSUE THREAD

**Issue by nodiscc** [az0/cleanerml#54]
Hi @az0, this took some time but we now have a bunch of good cleaners in the `release/` directory. Would you like to release a new bleachbit version with those cleaners added?

I see many people are not aware of this repository (eg. http://www.webupd8.org/2014/10/unity-privacy-indicator-04-released.html, see comments), and there is still no mechanism in bleachbit to add those (I just clone the repo and manually copy files, which is fine, but many people won't bother)

What do you think? It would be cool to have the well tested cleaners in Debian.

**Comment by theatre-x** [comment]
There's also a lot of cleaners in BB that I have never known anyone to use nor have used them myself. Maybe we could take some out and leave/add in some cleaners for more reknowned programs like Steam, Firefox, Flash, etc etc.

**Comment by mikevainio** [comment]
Better solution: Keep all, and have a folder branching from the cleaner folder which would have any cleaner files not in use (managed/moved by BleachBit). Of course this would require a new set of functions/code in BB. I already do this manually with my installs of BBS. Speeds up BB tremendously (winapp2.ini) and far less irrelevant checkboxes. Tse lesser known cleaners are benefits to anyone that does use them. Another reknown to add: KDE.

**Comment by nodiscc** [comment]
@az0 Is it still planned to move cleaners in https://github.com/az0/cleanerml/tree/master/release to  https://github.com/az0/bleachbit/tree/master/cleaners?

Thanks

**Comment by az0** [comment]
@nodiscc 
Rather than just shipping all the CleanerML cleaners with BleachBit, I'd like to make an online update system like BleachBit has today for Winapp2.ini. But I'd like to make it better than that.

**Comment by ROCKNROLLKID** [comment]
Plans for a CleanerML updater was created a some time ago here: https://bugs.launchpad.net/bleachbit/+bug/1448321

Keeping them in CleanerML would be better because then we can add the updater and people can get new cleaners as soon as they are ready, instead of waiting months for a new cleaner or a modified one.

I don't think this ticket is necessary anymore.

**Comment by nodiscc** [comment]
https://bugs.launchpad.net/bleachbit/+bug/1448321
