### ISSUE TITLE
Accessibility issue in Windows XP

### ISSUE THREAD

**Issue by theatre-x** [az0/cleanerml#57]
I have had a complaint said to me about how difficult it is to read the text in the progress bar in Bleachbit in Windows XP when using that tacky, default blue/green theme. The text is white. Maybe we could highlight the text in the progress bar to make it more readable?

**Comment by theatre-x** [comment]
The complainer is among the elderly FWIW.

**Comment by az0** [comment]
Right now the colors are the default theme in GTK+ version 2.  The best place to file this is here https://bugs.launchpad.net/bleachbit/ . This may be addressed with the GTK version 3 update
