### ISSUE TITLE
Keep cleaners in 'cleanerml' repo and not in 'bleachbit' repo

### ISSUE THREAD

**Issue by cfoellmann** [az0/cleanerml#68]
Wouldn't it be better for the cleaner xml files to stay in this repo and fetch the stable ones in the build process?
This way contributors could see in the repo if a cleaner for an app exists and can be extended or it needs to be created.

**Comment by cfoellmann** [comment]
do you @az0 see any way to allow loading the cleaners from this repo directly from the installed bleachbit app?

**Comment by az0** [comment]
The cleaners in the BleachBit repo should have a higher level of testing, maintenance, are more carefully translated, etc. than those in the CleanerML repository.

It is on my to-do list to allow over-the-Internet downloads from the CleanerML repository to theBleachBit app.
