### ISSUE TITLE
Firefox (CleanerML version)

### ISSUE THREAD

**Issue by BrunoReX** [az0/cleanerml#9]
Here's my attempt at porting the Firefox cleaner to CleanerML, with some additional directories added.

Tested on Windows 7 with Firefox Aurora 21.0a2 (2013-04-01).
There was a "thumbnails-old" folder that had almost 1GB of files on it.

Get it [here](https://gist.github.com/BrunoReX/5286414).

**Comment by nodiscc** [comment]
This issue will soon turn 1 year old. It overlaps with https://github.com/az0/cleanerml/issues/68 so we'd need to port all bleachbit cleaners to CleanerML, and @az0 could do a new Bleachbit release using only CleanerML cleaners.

Would someone start this porting task?

**Comment by tiemay** [comment]
@nodiscc you mean two years? I'll work on it.

**Comment by nodiscc** [comment]
Ref. https://github.com/az0/bleachbit/issues/138

**Comment by Tobias-B-Besemer** [comment]
Isn't the Firefox CleanerML version finished?

**Comment by az0** [comment]
Yes
